<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3store\models\base;

use Yii;

/**
 * This is the base-model class for table "store_woff".
 *
 * @property string $id
 * @property string $load_tran_id
 * @property string $unload_tran_id
 * @property string $quantity
 *
 * @property \d3yii2\d3store\models\StoreTransactions $loadTran
 * @property \d3yii2\d3store\models\StoreTransactions $unloadTran
 * @property string $aliasModel
 */
abstract class StoreWoff extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'store_woff';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['load_tran_id'], 'required'],
            [['load_tran_id', 'unload_tran_id'], 'integer'],
            [['quantity'], 'number'],
            [['load_tran_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3store\models\StoreTransactions::className(), 'targetAttribute' => ['load_tran_id' => 'id']],
            [['unload_tran_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3store\models\StoreTransactions::className(), 'targetAttribute' => ['unload_tran_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3store', 'ID'),
            'load_tran_id' => Yii::t('d3store', 'Load transaction'),
            'unload_tran_id' => Yii::t('d3store', 'Unload transaction'),
            'quantity' => Yii::t('d3store', 'Quantity'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoadTran()
    {
        return $this->hasOne(\d3yii2\d3store\models\StoreTransactions::className(), ['id' => 'load_tran_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUnloadTran()
    {
        return $this->hasOne(\d3yii2\d3store\models\StoreTransactions::className(), ['id' => 'unload_tran_id']);
    }


    
    /**
     * @inheritdoc
     * @return \d3yii2\d3store\models\StoreWoffQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \d3yii2\d3store\models\StoreWoffQuery(get_called_class());
    }


}
