<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3store\models\base;

use Yii;
use d3system\yii2\validators\D3TrimValidator;
use d3yii2\d3store\models\StoreTranAdd;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the base-model class for table "store_tran_add_type".
 *
 * @property integer $id
 * @property string $name
 * @property string $code
 *
 * @property StoreTranAdd[] $storeTranAdds
 * @property string $aliasModel
 */
abstract class StoreTranAddType extends ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'store_tran_add_type';
    }

    /**
     * @inheritdoc
     */
    public function rules(): array
    {
        return [
            'trimNumbers' => [['id'],D3TrimValidator::class, 'trimOnlyStringValues' => true],
            'required' => [['name', 'code'], 'required'],
            'tinyint Unsigned' => [['id'],'integer' ,'min' => 0 ,'max' => 255],
            [['name', 'code'], 'string', 'max' => 30]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels(): array
    {
        return [
            'id' => 'ID',
            'name' => 'Add type name',
            'code' => 'Add type code',
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getStoreTranAdds(): ActiveQuery
    {
        return $this
            ->hasMany(StoreTranAdd::class, ['type_id' => 'id']);
    }

}
