<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3store\models\base;

use Yii;

/**
 * This is the base-model class for table "store_ref".
 *
 * @property integer $id
 * @property string $name
 * @property string $class_name
 *
 * @property \d3yii2\d3store\models\StoreTransactions[] $storeTransactions
 * @property string $aliasModel
 */
abstract class StoreRef extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'store_ref';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'string', 'max' => 50],
            [['class_name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3store', 'ID'),
            'name' => Yii::t('d3store', 'Name'),
            'class_name' => Yii::t('d3store', 'Class Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStoreTransactions()
    {
        return $this->hasMany(\d3yii2\d3store\models\StoreTransactions::className(), ['ref_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \d3yii2\d3store\models\StoreRefQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \d3yii2\d3store\models\StoreRefQuery(get_called_class());
    }


}
