<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3store\models\base;

use d3yii2\d3store\models\DmMoveDelivery;
use d3yii2\d3store\models\SftSiftingDelivery;
use d3yii2\d3store\models\StoreTransactionsQuery;
use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the base-model class for table "store_transactions".
 *
 * @property string $id
 * @property string $action
 * @property string $tran_time
 * @property integer $stack_from
 * @property integer $stack_to
 * @property float $quantity
 * @property float $remain_quantity
 * @property integer $ref_id
 * @property string $ref_record_id
 * @property integer $add_ref_id
 * @property string $add_ref_record_id
 *
 * @property DmMoveDelivery[] $dmMoveDeliveries
 * @property SftSiftingDelivery[] $sftSiftingDeliveries
 * @property \d3yii2\d3store\models\StoreTransactionFlow[] $storeTransactionFlows
 * @property \d3yii2\d3store\models\StoreTransactionFlow[] $storeTransactionFlows0
 * @property \d3yii2\d3store\models\StoreStack $stackFrom
 * @property \d3yii2\d3store\models\StoreStack $stackTo
 * @property \d3yii2\d3store\models\StoreRef $ref
 * @property \d3yii2\d3store\models\StoreWoff[] $storeWoffs
 * @property \d3yii2\d3store\models\StoreWoff[] $storeWoffs0
 * @property string $aliasModel
 */
abstract class StoreTransactions extends ActiveRecord
{



    /**
    * ENUM field values
    */
    public const ACTION_LOAD = 'Load';
    public const ACTION_UNLOAD = 'Unload';
    public const ACTION_MOVE = 'Move';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'store_transactions';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['action', 'tran_time', 'quantity', 'remain_quantity'], 'required'],
            [['action'], 'string'],
            [['tran_time'], 'safe'],
            [['stack_from', 'stack_to', 'ref_id', 'ref_record_id', 'add_ref_id', 'add_ref_record_id'], 'integer'],
            [['quantity', 'remain_quantity'], 'number','min' => 0],
            [['stack_from'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3store\models\StoreStack::className(), 'targetAttribute' => ['stack_from' => 'id']],
            [['stack_to'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3store\models\StoreStack::className(), 'targetAttribute' => ['stack_to' => 'id']],
            [['ref_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3store\models\StoreRef::className(), 'targetAttribute' => ['ref_id' => 'id']],
            ['action', 'in', 'range' => [
                    self::ACTION_LOAD,
                    self::ACTION_UNLOAD,
                    self::ACTION_MOVE,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3store', 'ID'),
            'action' => Yii::t('d3store', 'Action'),
            'tran_time' => Yii::t('d3store', 'Time'),
            'stack_from' => Yii::t('d3store', 'From stack'),
            'stack_to' => Yii::t('d3store', 'To stack'),
            'quantity' => Yii::t('d3store', 'quantity'),
            'remain_quantity' => Yii::t('d3store', 'Remain quantity'),
            'ref_id' => Yii::t('d3store', 'Refernce model'),
            'ref_record_id' => Yii::t('d3store', 'Reference model record'),
            'add_ref_id' => Yii::t('d3store', 'Add Ref ID'),
            'add_ref_record_id' => Yii::t('d3store', 'Add Ref Record ID'),
        ];
    }


    /**
     * @return ActiveQuery
     */
    public function getStoreTransactionFlowsNext()
    {
        return $this->hasMany(\d3yii2\d3store\models\StoreTransactionFlow::className(), ['next_tran_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getStoreTransactionFlowsPrew()
    {
        return $this->hasMany(\d3yii2\d3store\models\StoreTransactionFlow::className(), ['prev_tran_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getStackFrom()
    {
        return $this->hasOne(\d3yii2\d3store\models\StoreStack::className(), ['id' => 'stack_from']);
    }

    /**
     * @return ActiveQuery
     */
    public function getStackTo()
    {
        return $this->hasOne(\d3yii2\d3store\models\StoreStack::className(), ['id' => 'stack_to']);
    }

    /**
     * @return ActiveQuery
     */
    public function getRef()
    {
        return $this->hasOne(\d3yii2\d3store\models\StoreRef::className(), ['id' => 'ref_id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getStoreWoffs()
    {
        return $this->hasMany(\d3yii2\d3store\models\StoreWoff::className(), ['load_tran_id' => 'id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getStoreWoffs0()
    {
        return $this->hasMany(\d3yii2\d3store\models\StoreWoff::className(), ['unload_tran_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return StoreTransactionsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new StoreTransactionsQuery(get_called_class());
    }


    /**
     * get column action enum value label
     * @param string $value
     * @return string
     */
    public static function getActionValueLabel($value){
        $labels = self::optsAction();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column action ENUM value labels
     * @return array
     */
    public static function optsAction()
    {
        return [
            self::ACTION_LOAD => Yii::t('d3store', self::ACTION_LOAD),
            self::ACTION_UNLOAD => Yii::t('d3store', self::ACTION_UNLOAD),
            self::ACTION_MOVE => Yii::t('d3store', self::ACTION_MOVE),
        ];
    }

}
