<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3store\models\base;

use d3system\dictionaries\SysModelsDictionary;
use d3yii2\d3store\models\SysModels;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the base-model class for table "store_fixes".
 *
 * @property integer $id
 * @property integer $transaction_id
 * @property string $time
 * @property integer $user_id
 * @property string $quantity
 * @property integer $ref_model_id
 * @property integer $ref_model_record_id
 *
 * @property SysModels $refModel
 * @property \d3yii2\d3store\models\StoreTransactions $transaction
 * @property string $aliasModel
 */
abstract class StoreFixes extends ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'store_fixes';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['transaction_id'], 'required'],
            'tinyint Unsigned' => [['ref_model_id'], 'integer', 'min' => 0, 'max' => 255],
            'integer Unsigned' => [['id', 'transaction_id', 'user_id', 'ref_model_record_id'], 'integer', 'min' => 0, 'max' => 4294967295],
            [['time'], 'safe'],
            [['quantity'], 'number'],
            ['ref_model_id', 'in', 'range' => array_keys(SysModelsDictionary::getClassList())],
            [['transaction_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3store\models\StoreTransactions::class, 'targetAttribute' => ['transaction_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'transaction_id' => 'Transaction ID',
            'time' => 'Time',
            'user_id' => 'User ID',
            'quantity' => 'Quantity',
            'ref_model_id' => 'Ref Model ID',
            'ref_model_record_id' => 'Ref Model Record ID',
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getRefModel()
    {
        return $this->hasOne(SysModels::class, ['id' => 'ref_model_id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getTransaction()
    {
        return $this->hasOne(\d3yii2\d3store\models\StoreTransactions::class, ['id' => 'transaction_id']);
    }

}
